apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: vip-customer-web
  namespace: vip-customer-app
spec:
  secretName: vip-customer-web
  duration: 2160h # 90d
  renewBefore: 360h # 15d
  isCA: false
  privateKey:
    algorithm: RSA
    encoding: PKCS1
    size: 2048
  usages:
    - server auth
    - client auth
  dnsNames:
    - "*"
  issuerRef:
    name: vip-customer-web
    kind: ClusterIssuer
    group: cert-manager.io