apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: vip-customer-web
spec:
  acme:
    email: <insert-your-email-here>
    server: https://acme-v02.api.letsencrypt.org/directory
    privateKeySecretRef:
      name: vip-customer-web
    solvers:
    - http01:
        ingress:
          class: istio